---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: soft-operator-flux-kustomization
  namespace: ghcr-flux-system
spec:
  interval: 1m0s
  path: ./kustomize
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: soft-operator-helm-repository
  targetNamespace: soft-operator
  timeout: 3m0s
  wait: true
