---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: soft-operator-helm-release
  namespace: ghcr-flux-system
spec:
  chart:
    spec:
      chart: soft-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: soft-operator-helm-repository
      version: '*'
  install:
    crds: Create
    createNamespace: true
  interval: 1m0s
  targetNamespace: soft-operator
  upgrade:
    crds: CreateReplace
