# permissions for end users to view memcacheds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: memcached-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: soft-serve
    app.kubernetes.io/part-of: soft-serve
    app.kubernetes.io/managed-by: kustomize
  name: memcached-viewer-role
rules:
- apiGroups:
  - cache.laidback.github.io
  resources:
  - memcacheds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.laidback.github.io
  resources:
  - memcacheds/status
  verbs:
  - get
