apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: soft-serve.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.laidback.github.io
      specDescriptors:
      - description: Port defines the port that will be used to init the container
          with the image
        displayName: Container Port
        path: containerPort
      - description: Size defines the number of Memcached instances
        displayName: Size
        path: size
      statusDescriptors:
      - description: Conditions store the status conditions of the Memcached instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: softer
  displayName: softer
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - lukas
  links:
  - name: Soft Serve
    url: https://soft-serve.domain
  maturity: alpha
  provider:
    name: lukas
  version: 0.0.0
